package dk.dtu.compute.se.pisd.roborally.client.Data;

import com.fasterxml.jackson.annotation.JsonProperty;
import dk.dtu.compute.se.pisd.roborally.client.HttpClientAsynchronousPost;

public class Games {
    @JsonProperty("game_id")
    private Long gameId; // Assuming game_id is autogenerated and Long type

    @JsonProperty("game_name")
    private String gameName;

    @JsonProperty("players_amount")
    private int playersAmount;

    @JsonProperty("joined_players")
    private int joinedPlayers;

    @JsonProperty("game_status")
    private int gameStatus;

    @JsonProperty("board_id")
    private Board board;

    // Getters and setters for non-autogenerated fields

    public void setGameId (Long gameId) {
        this.gameId = gameId;
    }
    public String getGameName() {
        return gameName;
    }

    public void setGameName(String gameName) {
        this.gameName = gameName;
    }

    public int getPlayersAmount() {
        return playersAmount;
    }

    public void setPlayersAmount(int playersAmount) {
        this.playersAmount = playersAmount;
    }

    public int getJoinedPlayers() {
        return joinedPlayers;
    }

    public void setJoinedPlayers(int joinedPlayers) {
        this.joinedPlayers = joinedPlayers;
    }

    public int getGameStatus() {
        return gameStatus;
    }

    public void setGameStatus(int gameStatus) {
        this.gameStatus = gameStatus;
    }

    public Board getBoard() {
        return board;
    }

    public void setBoard(Board board) {
        this.board = board;
    }

    // Getters for autogenerated fields
    public Long getGameId() {
        return gameId;
    }

    // No setter for gameId as it's autogenerated

    // toString method
    @Override
    public String toString() {
        return "Games{" +
                "gameId=" + gameId +
                ", gameName='" + gameName + '\'' +
                ", playersAmount=" + playersAmount +
                ", joinedPlayers=" + joinedPlayers +
                ", gameStatus=" + gameStatus +
                ", board=" + board +
                '}';
    }
}
