package dk.dtu.compute.se.pisd.roborally.client.Data;

import com.fasterxml.jackson.annotation.JsonProperty;

public class Players {

    @JsonProperty("player_id")
    private Long playerId; // Assuming game_id is autogenerated and Long type
    @JsonProperty("player_name")
    private String playerName;
    @JsonProperty("phase_status")
    private boolean phaseStatus;
    @JsonProperty("game_id")
    private Games game;

    public void setPlayerId (Long playerId) {
        this.playerId = playerId;
    }
    public Long getPlayerId() {
        return playerId;
    }
    public void setPlayerName(String playerName) {
        this.playerName = playerName;
    }
    public String getPlayerName() {
        return playerName;
    }
    public void setPhaseStatus(boolean phaseStatus) {
        this.phaseStatus = phaseStatus;
    }
    public boolean getPhaseStatus() {
        return phaseStatus;
    }
    public void setGame(Games game) {
        this.game = game;
    }
    public Games getGameID() {
        return game;
    }
    @Override
    public String toString() {
        return "Players{" +
                "playerId=" + playerId +
                ", playerName='" + playerName + '\'' +
                ", phaseStatus=" + phaseStatus +
                ", gameID=" + game +
                '}';
    }



}
