package dk.dtu.compute.se.pisd.roborally.client.Data;

import com.fasterxml.jackson.annotation.JsonProperty;

public class ProgCards {
    @JsonProperty("card_id")
    private int cardId; // Assuming game_id is autogenerated and Long type

    @JsonProperty("card_action")
    private String cardAction;
    @JsonProperty("executed_status")
    private String executedStatus;
    @JsonProperty("type")
    private String type;


    //CARD ID
    public void setCardId (int cardId) {
        this.cardId = cardId;
    }
    public int getCardId (int cardId) {
        return cardId;
    }

    //CARD ACTION
    public void setCardAction(String cardAction) {
        this.cardAction = cardAction;
    }
    public String getCardAction() {
        return cardAction;
    }

    //CARD EXECUTED STATUS
    public void setCardExecutedStatus(String cardExecutedStatus) {
        this.executedStatus = executedStatus;
    }
    public String getCardExecutedStatus() {
        return executedStatus;
    }

    //CARD TYPE
    public void setCardType(String type) {
        this.type = type;
    }
    public String getCardType() {
        return type;
    }


    @Override
    public String toString() {
        return "Cards{" +
                "cardId=" + cardId +
                ", cardAction=" + cardAction +
                ", executedStatus=" + executedStatus +
                ", type=" + type +
                '}';
    }


}
